paths: 
api/products/:
get: summary: obtiene todos los productos
tags: productos
responses: 
404: description: error al cargar los productos
200: description: los productos se obtuvieron correctamente




